

server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
#    Enable TLS SMTP MAIL
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

Cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    time: ${JWT_EXPIRATION_TIME}
password:
  reset:
    link: ${PASSWORD_RESET_LINK}






